### ISSUE TITLE
roots compile when using browserify due to missing module uglifyify

### ISSUE THREAD

**Issue by samccone** [carrot/roots-browserify#12]
I can PR this if you want...

**Comment by jenius** [comment]
Could you be a little more clear about what the issue actually is?

**Comment by samccone** [comment]
looks like doing a compressed compile using browserify it uses uglifyify .. but uglifyify is not a dep of this project

**Comment by samccone** [comment]
oh nm it is.. but seeing this issue still ... investigating

**Comment by samccone** [comment]
yeah this line... seems suspicious 

https://github.com/carrot/roots-browserify/blob/f62c1473b7bef43529c15f92c450f5ef4065f11c/lib/index.coffee#L46

looks like it is looking at my local node_modules and not deeply looking for it.. still not 100% why this is happening

**Comment by jenius** [comment]
Oh yeah maybe just require it and pass the object through directly instead of that string way of doing it then. I always thought that was suspect anyway, but browserify accepts transforms as strings then requires them, and it works in the tests which is why I left it. But see if changing that to the actual required library rather than a string works (that is a valid way to pass it, I only went with string because it worked and was less code)

**Comment by samccone** [comment]
yep for sure, I see why the tests work, but I can see why it does not work externally. cool beans

**Comment by jenius** [comment]
Did it work making that change though?

**Comment by jenius** [comment]
Merged and shipped as `0.3.0` :tada: -- thanks for catching this @samccone

**Comment by samccone** [comment]
bam
