### ISSUE TITLE
Output file is not Created

### ISSUE THREAD

**Issue by shwaydogg** [carrot/roots-browserify#16]
This is my app.coffee, I've tried every change I could think of, but public/js/build.js or any other build.js is not built:
```coffeescript
axis         = require 'axis'
rupture      = require 'rupture'
autoprefixer = require 'autoprefixer-stylus'
css_pipeline = require 'css-pipeline'
browserify = require 'roots-browserify' //replaces: js_pipeline  = require 'js-pipeline'

module.exports =
  ignores: ['assets/css/.master.styl.swp', '.app.coffee.swp', '**/.*.swp', 'readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

  extensions: [
    browserify(files: 'assets/js/**', out: 'js/build.js'),
    css_pipeline(files: ['assets/css/*.styl', 'assets/css/*.css'])
  ]

  stylus:
    use: [axis(), rupture(), autoprefixer()]
    sourcemap: true

  'coffee-script':
    sourcemap: true
```

**Comment by joshrowley** [comment]
Hi @shwaydogg , for the browserify extension, the `files` option should take either a string or an array of strings that point to files that will serve as the base of your require tree.

Usually, I do `browserify(files: 'assets/js/main.coffee', out: 'js/build.js')` and then use that `main.coffee` file to `require` in all my dependencies. Check out the [roots-browserify README](https://github.com/carrot/roots-browserify) for more info on what the options accept.

Minimatch strings are not supported though, so that's why it's the build file is not being created.

Closing this issue, but feel free to reopen if you run into any further difficulties.

**Comment by jenius** [comment]
Hey @shwaydogg did you go to Hamilton? Your name rings a bell :sparkles:

**Comment by shwaydogg** [comment]
Thanks @joshrowley !  I was able to get browserify going with that.  

Hey @jenius I didn't look at your real name until now, yeah we totally played Ultimate together, small world dude!  Enjoying roots, great project!

Sorry for delayed response guys, missed the email and realized I wasn't watching the rep until now so I didn't get the notification.

Was this the right place to post this question (or a similar Roots question in the roots repo) that's not a bug, but more throwing up a lifeline?

I was thinking about some ways to make the next steps after jumping on board with roots while not being an expert a bit more friendlier.  Let me know if you're interested!

**Comment by kylemac** [comment]
@shwaydogg if you use (or want to use) [slack](http://slack.com) you're welcome to join us in the roots slack room @ carrot. we've got a couple folks in there that are just trying it out, like yourself as well as a team of people to answer any questions you might have

**Comment by shwaydogg** [comment]
Thanks @kylemac, was there supposed to be a subdomain on that link?  carrot.slack.com  roots.slack carrot-roots.slack etc require passwords or don't exist....

**Comment by kylemac** [comment]
@shwaydogg i'll invite you if you're interested - what email should i use?

**Comment by shwaydogg** [comment]
schwedock+slack@gmail.com would be great, thanks again!

**Comment by kylemac** [comment]
@shwaydogg done. feel free to delete your previous msg if you don't want your email out there
