### ISSUE TITLE
Update insecure dependencies

### ISSUE THREAD

**Issue by J-Sek** [carrot/roots-browserify#33]
I use npms.io a lot and noticed some warnings:

![image](https://user-images.githubusercontent.com/20162853/27470400-0142ee0c-57f4-11e7-966f-169ec6130665.png)

These related to "insecure" include simple updates in package.json here and in roots-utils as displayed on [nodesecurity.io](https://nodesecurity.io/check/roots-browserify)

Definitely low priority and maybe it make more sense to handle all projects in Roots ecosystem...

**Comment by jescalan** [comment]
Yeah, so I'm not sure if you realized this so far, but roots is not actively maintained (there's a note about this in the readme). It has been succeeded by [spike](https://github.com/static-dev/spike), which is built by the same team, but is superior to roots in just about every way. Spike is also very actively maintained and developed. You might want to consider changing over!

If not, and you are still interested in roots, the responsibility to keep thing up to date is going to fall into the hands of contributors like yourself. Otherwise, we would warmly welcome you to the spike community! 👬

**Comment by J-Sek** [comment]
I must have missed that. Thanks :)

I've just started new project, so there should be no problem with migration.
